# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'


steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      MANIFEST="$(Build.SourcesDirectory)/app/src/main/AndroidManifest.xml"

      VERSIONNAME=`grep versionName ${MANIFEST} | sed 's/.*versionName\s*=\s*\"\([^\"]*\)\".*/\1/g'`

      echo "##vso[task.setvariable variable=some_string]${VERSIONNAME}"


- task: SlackNotification@6
  inputs:
    SlackApiToken: '$(Slack.ApiKey)'
    MessageAuthor: 'Azure DevOps'
    Channel: '#general'
    NotificationType: 'ChatMessage'
    Message: '$(some_string)'


