# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      MANIFEST="$(Build.SourcesDirectory)/app/src/main/AndroidManifest.xml"
      echo $(ls $(Build.SourcesDirectory))
      sudo find $(Build.SourcesDirectory) -print
      VERSIONNAME=`grep versionName ${MANIFEST} | sed 's/.*versionName\s*=\s*\"\([^\"]*\)\".*/\1/g'`
      VERSIONCODE=`grep versionCode ${MANIFEST} | sed 's/.*versionCode\s*=\s*\"\([^\"]*\)\".*/\1/g'`

      echo $VERSIONAME
      echo $VERSIONCODE
      echo test 
      echo "##vso[task.setvariable variable=some_string] New android stage build version $VERSIONNAME.$VERSIONCODE "
      curl -X POST  -H "Accept: Application/json" -H "Content-Type: application/json" https://hooks.slack.com/services/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 -d '{"text": " New android stage build version $VERSIONNAME.$VERSIONCODE "}'

      
   


- task: SlackNotification@6
  inputs:
    SlackApiToken: '$(Slack.ApiKey)'
    MessageAuthor: 'Azure DevOps'
    Channel: '#general'
    NotificationType: 'ChatMessage'
    Message: '<@U01S168AE2H> :angel::skin-tone-2:  $(some_string)'


